services:
  - name: postgres-backup-db
    type: cron
    schedule: "0 3 * * *"
    region: oregon
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIGITAL_OCEAN_ENDPOINT
        sync: false 
      - key: DIGITAL_OCEAN_BUCKET_NAME
        sync: false
      - key: DIGITAL_OCEAN_ACCESS_KEY
        sync: false
      - key: DIGITAL_OCEAN_SECRET_KEY
        sync: false
      # Postgres version of your Postgres instance 
      # For example, 16
      - key: POSTGRES_VERSION
        sync: false
      # Alpine base-OS version, see README
      # For example, 3.20
      - key: ALPINE_VERSION
        sync: false
      - key: FILE_PREFIX
        sync: false
  
